import puppeteer from 'puppeteer-core';
const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const b = await puppeteer.launch({ executablePath: CHROME, headless: 'new', args: ['--no-sandbox', '--disable-gpu', '--enable-unsafe-swiftshader', '--use-angle=swiftshader'] });
const p = await b.newPage();
await p.setViewport({ width: 1280, height: 720 });
await p.goto('http://127.0.0.1:5173/', { waitUntil: 'load', timeout: 30000 });
await new Promise((r) => setTimeout(r, 6000));
await p.screenshot({ path: 'shots/menu2.png' });
const title = await p.evaluate(() => document.querySelector('.panel h1')?.textContent || null);
const startBtn = await p.evaluate(() => document.querySelector('.panel button')?.textContent || null);
console.log('MENU_TITLE=' + title + ' BUTTON=' + startBtn);
await b.close();
